# Generated by Django 4.2.2 on 2023-07-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='bookitem',
            name='writer',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
