# Generated by Django 4.2.2 on 2023-07-13 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0002_alter_category_options_bookitem_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookitems', to='stok.category'),
        ),
    ]
